# Translations template for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-04-21 21:39+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.14.0\n"

#: app.py:45 app.py:82
msgid "Please provide user details"
msgstr ""

#: app.py:47 app.py:84
msgid "Bad request"
msgstr ""

#: app.py:61
msgid "User already exists"
msgstr ""

#: app.py:62 app.py:144 app.py:284
msgid "Conflict"
msgstr ""

#: app.py:66
msgid "Successfully created new user"
msgstr ""

#: app.py:71 app.py:108 app.py:174
msgid "Something went wrong"
msgstr ""

#: app.py:89 app.py:131 app.py:274
msgid "Invalid data"
msgstr ""

#: app.py:103
msgid "Successfully fetched auth token"
msgstr ""

#: app.py:112
msgid "Error fetching auth token!, invalid email or password"
msgstr ""

#: app.py:114 auth_middleware.py:21 auth_middleware.py:31
msgid "Unauthorized"
msgstr ""

#: app.py:118
msgid "Something went wrong!"
msgstr ""

#: app.py:133
msgid "Bad Request"
msgstr ""

#: app.py:142 app.py:152 app.py:282 app.py:292
msgid "failed to create a new data"
msgstr ""

#: app.py:147 app.py:287
msgid "successfully created a new data"
msgstr ""

#: app.py:164
msgid "data not found"
msgstr ""

#: app.py:166
msgid "Not Found"
msgstr ""

#: app.py:169 app.py:304
msgid "successfully retrieved a data"
msgstr ""

#: app.py:191
msgid "failed to retrieve all datas"
msgstr ""

#: app.py:203
msgid "successfully retrieved all data"
msgstr ""

#: app.py:208
msgid "failed to retrieve all data"
msgstr ""

#: app.py:221 app.py:249
msgid "data not found for user"
msgstr ""

#: app.py:223 app.py:251
msgid "Not found"
msgstr ""

#: app.py:230
msgid "successfully updated a data"
msgstr ""

#: app.py:235
msgid "failed to update a data"
msgstr ""

#: app.py:256
msgid "successfully deleted a data"
msgstr ""

#: app.py:261
msgid "failed to delete a data"
msgstr ""

#: app.py:309
msgid "failed to retrieve a data"
msgstr ""

#: app.py:324
msgid "The text record can't be null"
msgstr ""

#: app.py:348
msgid "Data not found"
msgstr ""

#: app.py:349 app.py:354
msgid "error"
msgstr ""

#: app.py:353
msgid "Data expired"
msgstr ""

#: app.py:361
msgid " shared the following with you"
msgstr ""

#: app.py:365
msgid "Password manager share function"
msgstr ""

#: app.py:366
msgid "copy"
msgstr ""

#: app.py:367
msgid "data copied to clipboard."
msgstr ""

#: app.py:379
msgid "Forbidden"
msgstr ""

#: app.py:387
msgid "Endpoint Not Found"
msgstr ""

#: auth_middleware.py:19
msgid "A token is required for access"
msgstr ""

#: auth_middleware.py:29
msgid "Token is not valid"
msgstr ""

#: auth_middleware.py:37
msgid "An error occurred during token validation"
msgstr ""

#: validate.py:30
msgid "Invalid email format"
msgstr ""

#: validate.py:33
msgid "Password is invalid."
msgstr ""

#: validate.py:36
msgid "Name must be between 2 and 30 words"
msgstr ""

#: validate.py:43
msgid "Email and Password is required"
msgstr ""

#: validate.py:46
msgid "Email format is incorrect"
msgstr ""

#: validate.py:49
msgid "Password does not meet the required standards"
msgstr ""

